### ISSUE TITLE
add a new data contributor role

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/frontend#103]
Besides the admin role in projects, we should add a new data contributor role. This role can only see and edit the datasets and labelings of a project.

**Comment by TobiasRoeddiger** [comment]
Are these roles different from subscription roles?

**Comment by KtrauM** [comment]
Subscription roles are independent of admin / data contributor roles. Former is user specific, latter is project specific, as the user can subscribe to a better plan for their projects and still be contributor to other projects.

**Comment by KtrauM** [comment]
How is this data contributor role different from the regular users in the project? Currently we have an admin and admin can add other users to project and they can work on the datasets, train models and deploy them. Is the envisioned data contributor role less privileged than the current regular user in the project, i. e. they can add/edit datasets but can't train/deploy?

**Comment by TobiasRoeddiger** [comment]
As you described, the idea of a data contributor role is to have the possibility to upload datasets but nothing else. Probably they should be limited to the datasets they uploaded to a project.
