### ISSUE TITLE
Add support for more browsers (Firefox) for the 'Record with Mobile Device' feature

### ISSUE THREAD

**Issue by omeryagmurlu** [edge-ml/frontend#109]
Currently we only support IOS Safari via DeviceMotion/OrientationEvent and Chrome via the Web Sensors API.

We can use DeviceMotionEvent to add support to more browsers, but it comes with a small catch: Even though the event name is same across all browsers, they handle coordinates differently from each other. This may cause problems if one uses different browsers in the same dataset. Since we are currently only using DeviceMotion for IOS Safari, we don't need to pay any attention to this.

![image](https://user-images.githubusercontent.com/8201544/181833769-ed58b38a-7bce-44ef-bf32-98601ebc0e16.png)

If we enable DeviceMotionEvent for every browser that supports it, we'll be able to support data recording from Firefox and have two different APIs on Chrome (both device motion and Web Sensors API)

I've already put together a PR for this feature, should I merge it?

**Comment by tk-king** [comment]
Check if we can unify the representations in terms of units and data ranges.

**Comment by omeryagmurlu** [comment]
I've recorded simultaneously on both chrome and firefox mobile, and couldn't find any differences between both in terms of coordinates or data ranges. It seems like the info on MDN is outdated and refers to a previous version of firefox mobile before it was rewritten in 2020.

The only differences I could find with my tests between both browsers are the sampling rates and precision they offer. Chrome returns values rounded to one digit after comma, whereas firefox mobile doesn't do any rounding. I don't think this is something we can (or should) fix.

[chrome.zip](https://github.com/edge-ml/frontend/files/9280931/chrome.zip)
[firefox.zip](https://github.com/edge-ml/frontend/files/9280932/firefox.zip)
