### ISSUE TITLE
Dataset view is slow

### ISSUE THREAD

**Issue by omeryagmurlu** [edge-ml/frontend#151]
I've identified the following problems:

- [ ] timeseries are loaded in their entirety (linked issue: #150)
- [ ] most operations involving timeseries (changing timeseries offset, fuse, onSetName, onSetUnit) work in the frontend, move them to backend
  - currently we load the whole dataset, modify it in frontend, and send it back to the backend. This won't work with streaming
- [ ]  (un)locking datasets needs multiple requests, reduce them to one

**Comment by tk-king** [comment]
Removed the locking feature.
