### ISSUE TITLE
UI Usability Improvements

### ISSUE THREAD

**Issue by tk-king** [edge-ml/frontend#160]
- [x] Modals: Cancel left (Esc), Save right (Enter)
- [x] Use Modals everywhere instead of alerts
- [ ] Live data view on record dataset page: Original sampling rate, improve look

**Comment by KtrauM** [comment]
I removed the cursor: pointer option for the dataset entries on the project overview page, because it makes the user assume you can click anywhere on the card and open the dataset when it is not the case.

**Comment by tk-king** [comment]
- [ ] Some colors of labels are not good visible: Maybe draw a frame around it / chnage text-color based on label-color...
![image](https://user-images.githubusercontent.com/30200721/220077168-b662aaff-f075-4739-a4e9-c5b943e1f47c.png)
![image](https://user-images.githubusercontent.com/30200721/220077269-09b504f6-f08f-4b06-9ca4-c51c4c6ba307.png)

- [ ] Shortcuts for labeling: Use keys (1,2,3,4,...) for selecting the label
- [ ] Use Delete / Backspace to delete a label

**Comment by tk-king** [comment]
- [ ] Make sure buttons have no animation when they are inactive
- [ ] Remove download all button when there are no datasets
