### ISSUE TITLE
Dataset-Labeling-Page Improvements

### ISSUE THREAD

**Issue by tk-king** [edge-ml/frontend#161]
- [ ] Make metadata-sidebar on right side collapsable to the top to have more width
- [x] LabelBar (bottom): Remove Id, Remove Unlock, Disable shifiting time series (three dots menu), 
- [x] Add Dropdown menu for labelings, remove labeling-bar (top)
- [x] top-bar: lock/unlock, from, to, select labeling (allow empty), download, delete, hep
- [x] bottom: labels
- [x] Remove Management from right side

**Comment by omeryagmurlu** [comment]
https://github.com/edge-ml/frontend/tree/feat/dataset-view-ui-improvements
