### ISSUE TITLE
Is it intended behavior that only the subset of labels belonging to a label is shown on the datasets overview page?

### ISSUE THREAD

**Issue by KtrauM** [edge-ml/frontend#171]
![image](https://user-images.githubusercontent.com/14796788/228625744-3fcfc580-1e46-4b3f-a489-414bb1b65b8b.png)

All 3 datasets in the example are labelled using the labeling 'Movement'. 
The first dataset has segments labeled with both 'Jump' and 'Stop'.
The second dataset has no labeled segments. This is achieved by uploading a .csv file with the labeling but without marking any timestamp to label.
The third dataset has segments labeled only with 'Jump'. This is achieved by uploading a .csv file without labeling and applying labeling on the website.

**Comment by tk-king** [comment]
It is intended behavior to only show the used labels for a lableing.
The second case, where no label is in the dataset should no occur. This is a bug in the dataset-upload / creation code. In this case we sould add the labeling to the db but not to the dataset.
