### ISSUE TITLE
Sticky buttons

### ISSUE THREAD

**Issue by tk-king** [edge-ml/frontend#175]
The styled edge-ml buttons are stuck in their "selected" state after clicking on them.

**Comment by omeryagmurlu** [comment]
This is appprently a feature of bootstrap: https://github.com/twbs/bootstrap/issues/12364

I've changed the style to make it look less like an eyesore, but the button that has the focus is still distinguishable (5% brightness difference only).

with focus:
![image](https://user-images.githubusercontent.com/8201544/233219710-f5ab2ed7-2fc6-4409-b34a-22c04af7ff05.png)

without:
![image](https://user-images.githubusercontent.com/8201544/233219853-e5b6c2f9-86d0-4248-9afe-0c7adc246de6.png)
