### ISSUE TITLE
Frontend crashes when deleting labels/labelings used in dataset

### ISSUE THREAD

**Issue by ilteen** [edge-ml/frontend#19]
After deleting some labels, the app crashed. Does not happen all the time...
<img width="1552" alt="Bildschirmfoto 2021-09-20 um 11 08 07" src="https://user-images.githubusercontent.com/35779536/133979510-f774c11e-bb2e-45f6-924d-ea4be8487f63.png">

**Comment by tk-king** [comment]
This happens because the Ids of the labels are still present in the dataset (and maybe in some other places in the backend).

**Comment by TobiasRoeddiger** [comment]
In that case, we should add logic that checks if the labelings are referenced by any of the datasets, warn the user that this will remove the labels from the datasets, and finally propagate the changes back to the dataset.

**Comment by ilteen** [comment]
Steps to reproduce: 
Create labeling with label(s), use this label to label the dataset, then:
-either go to labelings/edit and delete a label used in the dataset from this labeling
-or delete the used labeling entirely
 
Now when heading back to the dataset, the app will crash all the time, even so when deleting the dataset. Only entirely deleting dataset and all used labelings will get it to work again.
