### ISSUE TITLE
Disallow selecting incompatible datasets

### ISSUE THREAD

**Issue by tk-king** [edge-ml/frontend#196]
Some datasets are not compatible with each other during training. For example when they share no common time-series (by name).

- [x] Only use overlapping timeSeries between datasets. If the user selects datasets for which only a certain amount of timeSeries overlap, present this information
- [x] When there are no common timeSeries between the selected datasets, show this as a notification and prevent clicking on next.
- [x] Also reflect these changes in the backend and return an error when such a dataset combination is requested for model training.

**Comment by omeryagmurlu** [comment]
![image](https://github.com/edge-ml/frontend/assets/8201544/cff19919-c410-43a6-98e7-991f4f2d86d6)
