### ISSUE TITLE
Uploading CSV file with invalid labeling format will create invalid labelings

### ISSUE THREAD

**Issue by ilteen** [edge-ml/frontend#24]
In the provided CSV file, there's "label_label1" in the header, but there aren't any actual labels with this labeling. 
Such a file cannot be created from edge-ml, only externally, but uploading it results in the creation of a labeling without labels, which should never happen.
[invalid.csv](https:// github.com/edge-ml/frontend/files/7210218/invalid.csv)
<img width="939" alt="Bildschirmfoto 2021-09-22 um 13 24 41" src="https://user-images.githubusercontent.com/35779536/134335289-0a56c6ad-27f2-4cab-9ba9-d5002fad138f.png">

**Comment by TobiasRoeddiger** [comment]
Though it does not make a lot of sense we should support this edge case and make sure it doesn't crash the frontend.
