### ISSUE TITLE
when creating a project it fails silently if the user is not known

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/frontend#34]
when I create a project and write a username that does not exist, it will not save without showing any type of error message

also, it would be nice if the user that is creating the project is already added to the list of people in the project, otherwise it is confusing as people think they have to add themselves. for the user creating the project we hide the delete button and gray it out because it always has to be added.

**Comment by tk-king** [comment]
Now users can only add users from the dropdown menu to the project.
Added an admin text-field which shows the creating user as the admin of the new project.
