### ISSUE TITLE
Point users to GitHub so that they can report a problem

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/frontend#45]
Most likely students will find a bunch of bugs when using edge-ml during the lecture. We should point them to the GitHub issue page of the edge-ml main repo so they can report it there. Just add this small note to the different pages in the parent layout.

![image](https://user-images.githubusercontent.com/11386075/141327029-03e96c43-f263-42db-9fb1-ced900285e84.png)

**Comment by tk-king** [comment]
Added Report a bug button above documentation as an alternative.
![image](https://user-images.githubusercontent.com/30200721/142481410-55f22ee4-12f4-4d90-97f7-4406d8f637d0.png)
