### ISSUE TITLE
Plot in edge-ml not corresponding to plot of original CSV data

### ISSUE THREAD

**Issue by ilteen** [edge-ml/frontend#58]
In the provided CSV, the plots shown in edge ml do not correspond to the original plot. Edge-ml's plot e.g. only shows values between 0-1 and the waveform pattern is not visible at all.

![image](https://user-images.githubusercontent.com/35779536/143883298-a6e26154-3365-491e-996d-ac269c0b1aa2.jpg)

<img width="648" alt="Bildschirmfoto 2021-11-29 um 15 08 28" src="https://user-images.githubusercontent.com/35779536/143884062-5c1d87ff-5ff3-4652-9bd2-ca7d44624bb0.png">

[test_data_donwsample_200.csv](https://github.com/edge-ml/frontend/files/7618730/test_data_donwsample_200.csv)

**Comment by tk-king** [comment]
Uploded the data to app.edge-ml.org and got this plot for accX which looks more or less like the original data:

![image](https://user-images.githubusercontent.com/30200721/148740825-39973b28-7c03-43bb-a0bb-2607d95ce4f5.png)
