### ISSUE TITLE
timestamp error

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/frontend#59]
![image](https://user-images.githubusercontent.com/11386075/145212745-b8085e2e-6ebb-441e-b0fd-1f427bd69b5a.png)

This happend right after recording a new dataset on a freshly flashed nicla. First dataset had incorrect timestamp. Not exactly sure how to reproduce.

**Comment by TobiasRoeddiger** [comment]
Dataset is initialized with a start time 0, only once data is received the timstamp changes. 

possible solution will be to set the current time during init

**Comment by tk-king** [comment]
Could not reproduce this error:  Dataset is initialized with the current time + an offset.
