### ISSUE TITLE
Enable / Disable labels in plots

### ISSUE THREAD

**Issue by tk-king** [edge-ml/frontend#62]
When a plot contains many labels it looks a bit cluttered: 

![image](https://user-images.githubusercontent.com/30200721/148741453-8c629495-7f92-40e6-bbcf-8590c3f06617.png)

A possible improvement would be to add a little dropdown menu to select / deselect the labels which are drawn.

**Comment by TobiasRoeddiger** [comment]
This should be combined with fixing the toolbar for labels. They should not overlap with the right sidebar.
