### ISSUE TITLE
Uploading .csv files fail on the latest version

### ISSUE THREAD

**Issue by KtrauM** [edge-ml/frontend#63]
I can reproduce this error using this [Long.csv](https://github.com/edge-ml/frontend/files/7890322/Long.csv) file which is created on the beta version. The file can be uploaded to https://app.edge-ml.org, but does not work on beta. I am using Windows 10 and Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by KtrauM** [comment]
The issue is related to the labelings, as the file can be uploaded if you delete the labeling during upload.

**Comment by tk-king** [comment]
Seems to work right now on app.edge-ml.org
