### ISSUE TITLE
show labels behind labeling in training tab

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/frontend#64]
Would be nice to show the labels as colored boxes here. Similar how we have them at the labelings page (second screenshot).

![image](https://user-images.githubusercontent.com/11386075/150102160-2d4ea868-c3ee-4324-a157-4c4fa184bb95.png)

![image](https://user-images.githubusercontent.com/11386075/150102201-fa163f53-76d7-489a-b451-33adcb01ce39.png)

@tk-king or @KtrauM let me know who would like to take this over :)

**Comment by tk-king** [comment]
I could work on this.

**Comment by TobiasRoeddiger** [comment]
Perfect, thanks.
