### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/frontend#66]

**Comment by tk-king** [comment]
At the moment the master branch does not seem to be in a state suitable for release. We have to move the commits for the real time data graph display feature to a seperate branch so we can add google analytics and publish the changes.

**Comment by TobiasRoeddiger** [comment]
@pir-anja can you please create a new branch for the real time data graph and remove the partially working changes from master?

In the future, a seperate branch should be created for unstable features.

**Comment by tk-king** [comment]
Deployed Google Analytics on the production server.
