### ISSUE TITLE
show "TBD" or something similar while a model is training for performance in the validation tab

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/frontend#69]
Currently we are lacking feedback after a user has clicked on the train model button. A first step to mitigate this problem could be to switch to the deployment tab after training was clicked. Here we show the model without the performance metrics (just write "TBD" or pending or whatever because they are still computed. 

We would have the untrained model in the list then which shows that user something is happening.

**Comment by omeryagmurlu** [comment]
![image](https://user-images.githubusercontent.com/8201544/165043676-03010bad-fe30-49ac-8772-c04f1513b91f.png)

**Comment by TobiasRoeddiger** [comment]
very cool, are these steps on a per model basis?

**Comment by omeryagmurlu** [comment]
yes, for every model there is a new entry with it's own steps

**Comment by TobiasRoeddiger** [comment]
Awesome, great job.

**Comment by omeryagmurlu** [comment]
oh, I understood the question wrong. All classifiers have the same steps currently, but I think the design doesn't depend very much on that fact, so we could change it when we need it

**Comment by TobiasRoeddiger** [comment]
Cool, let's do it now then :)

**Comment by TobiasRoeddiger** [comment]
![image](https://user-images.githubusercontent.com/11386075/167416289-18abe553-5b0d-4a6f-8d8b-e5a72d29faec.png)
the ongoing trainings are currently not shown on a per project level

**Comment by omeryagmurlu** [comment]
https://github.com/edge-ml/ml/commit/c6164cecbd522ee4c5595f019a09441b8c01c335
