### ISSUE TITLE
Validation Page improvements

### ISSUE THREAD

**Issue by omeryagmurlu** [edge-ml/frontend#70]
Fix
- [x] change tab icon to https://fontawesome.com/v5.15/icons/check?style=solid
- [x] use rounded percentage values for numbers

Feature
- [ ] change details modal to be a new page on it's own
- [x] add storage consumption item to the detail page
- [x] delete models

Maybe
- [x] plot confusion matrix

**Comment by TobiasRoeddiger** [comment]
+1 for plotting the confusion matrix

**Comment by TobiasRoeddiger** [comment]
modal is fine
