### ISSUE TITLE
Improved Unlock Button

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/frontend#81]
the unlock button is hard to find / use. it would be nice if by default, a dataset is unlocked, and then once you want to lock it you can click lock. and this settings will then be saved when you load the dataset again (store the locked optiok in the backend).

**Comment by omeryagmurlu** [comment]
https://github.com/edge-ml/frontend/commit/649ccaa1238e3cef465d0ce93a181f387cb6d7d4
https://github.com/edge-ml/backend/commit/1e7de47a2d7e164092c2c7868e6a5ab99a9f2df4
https://github.com/edge-ml/backend/commit/aa3a4fe8515db0af1dda60190db39641a4725a24
