### ISSUE TITLE
CSV upload

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/frontend#85]
currently, uploading a CSV file larger than 50 MB failes silently (error in console) => catch error and show a message to the user

**Comment by omeryagmurlu** [comment]
I couldn't replicate the issue, uploading >50 MB files results in this error message: 
![image](https://user-images.githubusercontent.com/8201544/163732455-0ad8953d-2a04-428f-8dd1-f56f611ea3af.png)

I'll make the error message a little more explaining
