### ISSUE TITLE
Data loss when recording data over BLE.

### ISSUE THREAD

**Issue by tk-king** [edge-ml/frontend#87]
When recording data over BLE, some data can get lost when the tab / browser is inactive.
Maybe this only occurs when the notebook is running on battery power.

**Comment by TobiasRoeddiger** [comment]
hotefix: show warning when the user switches the tab and let them confirm? is it only during tab switches or also when the browser is in the background?

warning should only show once before page is reloaded to avoid annoying the user

**Comment by tk-king** [comment]
I am not quite sure when exactly this happens. I just found the execution of js code is being stopped when the browser is running in the background. 

Warning the user could prevent the problem for now.

**Comment by TobiasRoeddiger** [comment]
Per default I would guess js code keeps running even after tab switches. Are we using setInterval or any related functions?

**Comment by TobiasRoeddiger** [comment]
Did we ever look into this issue @tk-king ?

**Comment by tk-king** [comment]
Yes we did, but the exact reason for the data loss could not be determined yet as the behavior seems to be inconsistent, at least on my machine.
