### ISSUE TITLE
Labeling creation has ambigious wording.

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/frontend#9]
Creating a new labeling is a little confusing at the moment. First, we set a name for the labeling, then we add the specific labels which is a bit unclear. When I use it I'm always tempted to just click save after defining the name. Therefore my suggestion is to clarify the wording as follows:
- in the labeling overview table change the "+ Add" button to "+ Add Labeling Set"
- change the header of the modal to "Add Labeling Set"
- change "Name" to "Labeling Set Name"
- change the "+Add" button in the modal to "+ Add Label"

![image](https://user-images.githubusercontent.com/11386075/133684304-20bcbf69-c6e8-4750-88ce-3362f5e41420.png)

**Comment by ilteen** [comment]
There is actually a real bug to this as well: When adding a new labeling without any label, and then trying to label the data with this labeling, the app crashes, because it expects a label. I will also address this.

**Comment by ilteen** [comment]
I pushed the updated wording on the labels branch. Still working on the crash.
