### ISSUE TITLE
Allow deselection of labels inside one category

### ISSUE THREAD

**Issue by riedel** [edge-ml/frontend#94]
![grafik](https://user-images.githubusercontent.com/566485/169256184-547cd5b4-4173-4444-8bb2-5e46d279c552.png)

**Comment by TobiasRoeddiger** [comment]
@KtrauM can we add checkboxes inside the labels please, for other it is disabled by default
![image](https://user-images.githubusercontent.com/11386075/169257513-7b67cd0c-11a8-4504-993b-550ebadce793.png)
