### ISSUE TITLE
Show contained labels and meta data in dataset overview

### ISSUE THREAD

**Issue by riedel** [edge-ml/frontend#97]
I have no clue how to distiguish those

![grafik](https://user-images.githubusercontent.com/566485/169258650-6186706f-b43a-4266-bcee-a3672a9f998f.png)

while there is custom metadata

![grafik](https://user-images.githubusercontent.com/566485/169258815-53f5f19f-6da0-4c1f-a6dc-95406fb0e71a.png)

and only one label inside

**Comment by riedel** [comment]
like I said in the title the meta data and the contained labels will help

**Comment by tk-king** [comment]
- Add accordion to each row in the list to show the metadata and labels.
- Add button to expand all rows at once to get an overview over the datasets

**Comment by tk-king** [comment]
Implemented in #117
