### ISSUE TITLE
No information in GUI what "fuse multiple timeseries" does

### ISSUE THREAD

**Issue by riedel** [edge-ml/frontend#98]
Background: i removed the original ts after fusing...

**Comment by riedel** [comment]
Maybe call it rather "view grouped" or something and do as you suggested... . Deleting the view should then recreate the channels I guess first

**Comment by tk-king** [comment]
- Make fused series look different and indicate that it is just a view
- Output warning when deleting a timeSeries that is included in a fused series
- Rename function to View grouped

**Comment by tk-king** [comment]
Removed the feature to reduce errors.
